name: Auto Update Blacklist

# Her saat çalıştır ve manuel tetikleme
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    permissions:
      contents: write  # push izni

    steps:
      # Repo’yu klonla
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python kur
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Gerekli kütüphaneleri yükle
      - name: Install dependencies
        run: |
          pip install requests tqdm

    # Her iki script'i sırayla çalıştır
      - name: Run Python scripts
        run: |
          python update_blacklist.py
          python sha256Bot.py
        

      # Değişiklikleri commit ve push et (pull ile rebase eklenmiş)
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update blacklist" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
